graph TD
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_offline_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,mlcommons,inference,src
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,mlperf,inference,utils
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,dataset-aux,imagenet-aux
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_onnxruntime,_resnet50,_offline_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_onnxruntime,_resnet50,_offline_) --> detect,cpu
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_onnxruntime,_resnet50,_offline_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_onnxruntime,_resnet50,_offline_) --> get,loadgen
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_onnxruntime,_resnet50,_offline_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_onnxruntime,_resnet50,_offline_) --> get,lib,onnxruntime,lang-cpp,_cpu
    get-preprocessed-dataset-imagenet,f259d490bbaf45f5_(_NCHW,_full_) --> get,python3
    get-preprocessed-dataset-imagenet,f259d490bbaf45f5_(_NCHW,_full_) --> get,dataset,image-classification,original,_full
    get-preprocessed-dataset-imagenet,f259d490bbaf45f5_(_NCHW,_full_) --> get,dataset-aux,image-classification,imagenet-aux
    get-generic-python-lib,94b62a682bc44791_(_package.opencv-python-headless_) --> get,python3
    get-preprocessed-dataset-imagenet,f259d490bbaf45f5_(_NCHW,_full_) --> get,generic-python-lib,_package.opencv-python-headless
    get-generic-python-lib,94b62a682bc44791_(_pillow_) --> get,python3
    get-preprocessed-dataset-imagenet,f259d490bbaf45f5_(_NCHW,_full_) --> get,generic-python-lib,_pillow
    get-preprocessed-dataset-imagenet,f259d490bbaf45f5_(_NCHW,_full_) --> mlperf,mlcommons,inference,source,src
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_onnxruntime,_resnet50,_offline_) --> get,dataset,preprocessed,imagenet,_NCHW,_full
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_onnxruntime,_resnet50,_offline_) --> get,ml-model,raw,resnet50,_onnx
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_onnxruntime,_resnet50,_offline_) --> generate,user-conf,mlperf,inference