graph TD
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_bert-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_bert-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_bert-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,python
    get-mlperf-inference-src,4b57186581024797_(_deeplearningexamples_) --> detect,os
    get-mlperf-inference-src,4b57186581024797_(_deeplearningexamples_) --> get,python3
    get-git-repo,ed603e7292974f10_(_branch.master,_repo.https://github.com/mlcommons/inference,_submodules.language/bert/DeepLearningExamples_) --> detect,os
    get-mlperf-inference-src,4b57186581024797_(_deeplearningexamples_) --> get,git,repo,_branch.master,_repo.https://github.com/mlcommons/inference,_submodules.language/bert/DeepLearningExamples
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_bert-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,mlcommons,inference,src,_deeplearningexamples
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_bert-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> pull,git,repo
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src,_deeplearningexamples
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_bert-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,mlperf,inference,utils
    get-cuda,46d133d9ef92422d_(_toolkit_) --> detect,os
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,generic-python-lib,_pip
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_bert-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,cuda-devices,_with-pycuda
    get-dataset-squad,6651c119c3ae49b3 --> get,sys-utils-cm
    download-file,9cdc8dc41aae437e_(_wget,_url.https://raw.githubusercontent.com/rajpurkar/SQuAD-explorer/master/dataset/dev-v1.1.json_) --> detect,os
    download-and-extract,c67e81a4ce2649f5_(_wget,_url.https://raw.githubusercontent.com/rajpurkar/SQuAD-explorer/master/dataset/dev-v1.1.json_) --> download,file,_wget,_url.https://raw.githubusercontent.com/rajpurkar/SQuAD-explorer/master/dataset/dev-v1.1.json
    get-dataset-squad,6651c119c3ae49b3 --> download-and-extract,_wget,_url.https://raw.githubusercontent.com/rajpurkar/SQuAD-explorer/master/dataset/dev-v1.1.json
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_bert-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,dataset,squad,language-processing
    download-file,9cdc8dc41aae437e_(_wget,_url.https://zenodo.org/record/3733868/files/vocab.txt_) --> detect,os
    download-and-extract,c67e81a4ce2649f5_(_wget,_url.https://zenodo.org/record/3733868/files/vocab.txt_) --> download,file,_wget,_url.https://zenodo.org/record/3733868/files/vocab.txt
    get-dataset-squad-vocab,e38874fff5094577 --> download-and-extract,_wget,_url.https://zenodo.org/record/3733868/files/vocab.txt
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_bert-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,dataset-aux,squad-vocab
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_mlperf_logging
    download-file,9cdc8dc41aae437e_(_cmutil,_url.https://armi.in/files/model.onnx_) --> detect,os
    download-and-extract,c67e81a4ce2649f5_(_url.https://armi.in/files/model.onnx_) --> download,file,_cmutil,_url.https://armi.in/files/model.onnx
    get-ml-model-bert-large-squad,5e865dbdc65949d2_(_onnx,_fp32_) --> download-and-extract,_url.https://armi.in/files/model.onnx
    get-ml-model-bert-large-squad,5e865dbdc65949d2_(_onnx,_fp32_) --> get,dataset-aux,squad-vocab
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,ml-model,bert,_onnx,_fp32
    download-file,9cdc8dc41aae437e_(_cmutil,_url.https://armi.in/files/bert_large_v1_1_fake_quant.onnx_) --> detect,os
    download-and-extract,c67e81a4ce2649f5_(_url.https://armi.in/files/bert_large_v1_1_fake_quant.onnx_) --> download,file,_cmutil,_url.https://armi.in/files/bert_large_v1_1_fake_quant.onnx
    get-ml-model-bert-large-squad,5e865dbdc65949d2_(_onnx,_int8_) --> download-and-extract,_url.https://armi.in/files/bert_large_v1_1_fake_quant.onnx
    get-ml-model-bert-large-squad,5e865dbdc65949d2_(_onnx,_int8_) --> get,dataset-aux,squad-vocab
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,ml-model,bert,_onnx,_int8
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,squad-vocab
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,mlcommons,inference,src,_deeplearningexamples
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> pull,git,repo
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src,_deeplearningexamples
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> generate,user-conf,mlperf,inference
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_package.pycuda
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,cuda,_cudnn
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,tensorrt
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> detect,cpu
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,sys-utils-cm
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,cuda,_cudnn
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,tensorrt,_dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,gcc
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,cmake
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_glog-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_gflags-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_libgmock-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_libre2-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_libnuma-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_libboost-all-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_rapidjson-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    get-generic-python-lib,94b62a682bc44791_(_package.pybind11_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_package.pybind11
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> get,generic-python-lib,_pip
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> get,cuda
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_pycuda
    get-generic-python-lib,94b62a682bc44791_(_opencv-python_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_opencv-python
    get-generic-python-lib,94b62a682bc44791_(_nvidia-dali_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_nvidia-dali
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_nlohmann-json3-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_git-lfs
    get-generic-python-lib,94b62a682bc44791_(_package.torch,_whl-url.https://github.com/mlcommons/cm4mlperf-inference/releases/download/mlperf-inference-v4.0/torch-2.1.0a0+git32f93b1-cp38-cp38-linux_x86_64.whl_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_package.torch,_whl-url.https://github.com/mlcommons/cm4mlperf-inference/releases/download/mlperf-inference-v4.0/torch-2.1.0a0+git32f93b1-cp38-cp38-linux_x86_64.whl
    get-generic-python-lib,94b62a682bc44791_(_package.torchvision,_whl-url.https://github.com/mlcommons/cm4mlperf-inference/releases/download/mlperf-inference-v4.0/torchvision-0.16.0a0+657027f-cp38-cp38-linux_x86_64.whl_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_package.torchvision,_whl-url.https://github.com/mlcommons/cm4mlperf-inference/releases/download/mlperf-inference-v4.0/torchvision-0.16.0a0+657027f-cp38-cp38-linux_x86_64.whl
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> detect,cpu
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,sys-utils-cm
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,python3
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,cuda,_cudnn
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,tensorrt
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,cmake
    get-generic-python-lib,94b62a682bc44791_(_requests_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_requests_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_requests_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_requests_) --> get,generic-python-lib,_pip
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic-python-lib,_requests
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_glog-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_gflags-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_libre2-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_libnuma-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_libboost-all-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_rapidjson-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> get,python3
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic-python-lib,_pycuda
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> add,custom,system,nvidia,_mlcommons
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> build,nvidia,inference,server,_mlcommons
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,ml-model,bert,_onnx,_fp32
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,ml-model,bert,_onnx,_int8
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,squad-vocab
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,mlcommons,inference,src,_deeplearningexamples
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> pull,git,repo
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,generic-python-lib,_package.pycuda
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,cuda,_cudnn
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,tensorrt
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> build,nvidia,inference,server,_mlcommons
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,ml-model,bert,_onnx,_fp32
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,ml-model,bert,_onnx,_int8
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,squad-vocab
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,mlcommons,inference,src,_deeplearningexamples
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> pull,git,repo
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_safetensors_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_safetensors_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_safetensors_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_safetensors_) --> get,generic-python-lib,_pip
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,generic-python-lib,_safetensors
    get-generic-python-lib,94b62a682bc44791_(_onnx_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_onnx_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_onnx_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_onnx_) --> get,generic-python-lib,_pip
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,generic-python-lib,_onnx
    get-generic-python-lib,94b62a682bc44791_(_package.sympy_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.sympy_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.sympy_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.sympy_) --> get,generic-python-lib,_pip
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,generic-python-lib,_package.sympy
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> get,generic-python-lib,_onnx-graphsurgeon
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev_) --> save,mlperf,inference,state
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> reproduce,mlperf,inference,nvidia,harness,_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_safetensors_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,generic-python-lib,_safetensors
    get-generic-python-lib,94b62a682bc44791_(_onnx_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,generic-python-lib,_onnx
    get-generic-python-lib,94b62a682bc44791_(_package.sympy_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,generic-python-lib,_package.sympy
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> get,generic-python-lib,_onnx-graphsurgeon
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev_) --> save,mlperf,inference,state
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> reproduce,mlperf,inference,nvidia,harness,_build_engine,_cuda,_bert-99.9,_singlestream,_tensorrt,_batch_size.1,_bert_,_v4.1-dev
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> reproduce,mlperf,inference,nvidia,harness,_preprocess_data,_cuda,_bert-99.9,_tensorrt,_bert_,_v4.1-dev
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_safetensors_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_safetensors
    get-generic-python-lib,94b62a682bc44791_(_onnx_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_onnx
    get-generic-python-lib,94b62a682bc44791_(_package.sympy_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_package.sympy
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_onnx-graphsurgeon
    detect-cpu,586c8a43320142f7 --> detect,os
    benchmark-program,19f369ef47084895 --> detect,cpu
    benchmark-program-mlperf,cfff0132a8aa4018 --> benchmark-program,program
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_cuda,_bert-99.9,_singlestream,_tensorrt,_rtx_4090_) --> benchmark-mlperf