#!/bin/bash

export MLC_GIT_CHECKOUT_PATH="/home/ubuntu/MLC/repos/local/cache/get-git-repo_589b92f1/repo"
export MLC_GIT_PUSH_CMD="git push"
export MLC_GIT_REPO_CHECKOUT=""
export MLC_GIT_REPO_CHECKOUT_FOLDER="repo"
export MLC_GIT_REPO_CHECKOUT_PATH="/home/ubuntu/MLC/repos/local/cache/get-git-repo_589b92f1/repo"
export MLC_GIT_REPO_CURRENT_HASH="e0908c410515842645c2e733c782507448fdea37"
export MLC_GIT_REPO_DEPTH="--depth 5"
export MLC_GIT_REPO_NAME="mlperf_inference_submissions_v5.0"
export MLC_GIT_REPO_PATCH="no"
export MLC_GIT_REPO_RECURSE_SUBMODULES=" --recurse-submodules"
export MLC_GIT_REPO_URL="https://github.com/seemamp002/mlperf_inference_submissions_v5.0"
export MLC_MLPERF_INFERENCE_SUBMISSION_DIR="/home/ubuntu/MLC/repos/local/cache/get-mlperf-inference-submission-dir_1f8fed7d/mlperf-inference-submission"
export MLC_MLPERF_INFERENCE_SUBMISSION_VERSION="4_1-dev"
export MLC_MLPERF_RESULTS_GIT_REPO_URL="https://github.com/seemamp002/mlperf_inference_submissions_v5.0"
export MLC_MLPERF_RESULTS_REPO_COMMIT_MESSAGE="Results on aws_c8g.4xlarge"
export MLC_PYTHON_BIN="python3"
export MLC_PYTHON_BIN_PATH="/home/ubuntu/mlcflow/bin"
export MLC_PYTHON_BIN_WITH_PATH="/home/ubuntu/mlcflow/bin/python3"
export MLC_PYTHON_CACHE_TAGS="version-3.12.3,non-virtual"
export MLC_PYTHON_MAJOR_VERSION="3"
export MLC_PYTHON_MINOR_VERSION="12"
export MLC_PYTHON_PATCH_VERSION="3"
export MLC_PYTHON_VERSION="3.12.3"
export MLC_QUIET="yes"
export MLC_RSYNC_VERSION="rsync  version 3.2.7"
export MLC_TMP_CURRENT_PATH="/home/ubuntu/MLC/repos/local/cache/get-git-repo_589b92f1/repo"
export MLC_TMP_CURRENT_SCRIPT_PATH="/home/ubuntu/MLC/repos/gateoverflow@mlperf-automations/script/push-mlperf-inference-results-to-github"
export MLC_TMP_CURRENT_SCRIPT_REPO_PATH="/home/ubuntu/MLC/repos/gateoverflow@mlperf-automations"
export MLC_TMP_CURRENT_SCRIPT_REPO_PATH_WITH_PREFIX="/home/ubuntu/MLC/repos/gateoverflow@mlperf-automations"
export MLC_TMP_CURRENT_SCRIPT_WORK_PATH="/home/ubuntu/MLC/repos/local/cache/get-git-repo_589b92f1/repo"
export MLC_TMP_PIP_VERSION_STRING=""


. "/home/ubuntu/MLC/repos/gateoverflow@mlperf-automations/script/push-mlperf-inference-results-to-github/run.sh"
