#!/bin/bash

export MLC_GIT_CHECKOUT_PATH="/home/kingjuno/MLC/repos/local/cache/get-git-repo_0ceb374a/repo"
export MLC_GIT_PUSH_CMD="git push"
export MLC_GIT_REPO_CHECKOUT=""
export MLC_GIT_REPO_CHECKOUT_FOLDER="repo"
export MLC_GIT_REPO_CHECKOUT_PATH="/home/kingjuno/MLC/repos/local/cache/get-git-repo_0ceb374a/repo"
export MLC_GIT_REPO_CURRENT_HASH="d98fc70d930ec9972cf061b379aeb1bbb2a8cba9"
export MLC_GIT_REPO_DEPTH="--depth 5"
export MLC_GIT_REPO_NAME="mlperf_inference_submissions_v5.0"
export MLC_GIT_REPO_PATCH="no"
export MLC_GIT_REPO_RECURSE_SUBMODULES=" --recurse-submodules"
export MLC_GIT_REPO_URL="https://github.com/kingjuno/mlperf_inference_submissions_v5.0"
export MLC_MLPERF_INFERENCE_SUBMISSION_DIR="/home/kingjuno/MLC/repos/local/cache/get-mlperf-inference-submission-dir_8a40fa5b/mlperf-inference-submission"
export MLC_MLPERF_INFERENCE_SUBMISSION_VERSION="4_1-dev"
export MLC_MLPERF_RESULTS_GIT_REPO_URL="https://github.com/kingjuno/mlperf_inference_submissions_v5.0"
export MLC_MLPERF_RESULTS_REPO_COMMIT_MESSAGE="Results on Azure added by Geo"
export MLC_PYTHON_BIN="python3"
export MLC_PYTHON_BIN_PATH="/home/kingjuno/mlc/bin"
export MLC_PYTHON_BIN_WITH_PATH="/home/kingjuno/mlc/bin/python3"
export MLC_PYTHON_CACHE_TAGS="version-3.10.12,non-virtual"
export MLC_PYTHON_MAJOR_VERSION="3"
export MLC_PYTHON_MINOR_VERSION="10"
export MLC_PYTHON_PATCH_VERSION="12"
export MLC_PYTHON_VERSION="3.10.12"
export MLC_QUIET="yes"
export MLC_RSYNC_VERSION="rsync  version 3.2.7"
export MLC_TMP_CURRENT_PATH="/home/kingjuno/MLC/repos/local/cache/get-git-repo_0ceb374a/repo"
export MLC_TMP_CURRENT_SCRIPT_PATH="/home/kingjuno/MLC/repos/mlcommons@mlperf-automations/script/push-mlperf-inference-results-to-github"
export MLC_TMP_CURRENT_SCRIPT_REPO_PATH="/home/kingjuno/MLC/repos/mlcommons@mlperf-automations"
export MLC_TMP_CURRENT_SCRIPT_REPO_PATH_WITH_PREFIX="/home/kingjuno/MLC/repos/mlcommons@mlperf-automations"
export MLC_TMP_CURRENT_SCRIPT_WORK_PATH="/home/kingjuno/MLC/repos/local/cache/get-git-repo_0ceb374a/repo"
export MLC_TMP_PIP_VERSION_STRING=""


. "/home/kingjuno/MLC/repos/mlcommons@mlperf-automations/script/push-mlperf-inference-results-to-github/run.sh"
