graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_bert-99,_deepsparse,_cpu,_valid,_r5.0-dev_default,_int8,_offline_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_bert-99,_deepsparse,_cpu,_valid,_r5.0-dev_default,_int8,_offline_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_bert-99,_deepsparse,_cpu,_valid,_r5.0-dev_default,_int8,_offline_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_reference,_bert-99,_deepsparse,_cpu,_valid,_r5.0-dev_default,_int8,_offline_) --> get,mlcommons,inference,src,_deeplearningexamples
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src,_deeplearningexamples
    app-mlperf-inference,d775cac873ee4231_(_reference,_bert-99,_deepsparse,_cpu,_valid,_r5.0-dev_default,_int8,_offline_) --> get,mlperf,inference,utils
    app-mlperf-inference,d775cac873ee4231_(_reference,_bert-99,_deepsparse,_cpu,_valid,_r5.0-dev_default,_int8,_offline_) --> get,dataset,squad,language-processing
    app-mlperf-inference,d775cac873ee4231_(_reference,_bert-99,_deepsparse,_cpu,_valid,_r5.0-dev_default,_int8,_offline_) --> get,dataset-aux,squad-vocab
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,python
    get-generic-python-lib,94b62a682bc44791_(_torch_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,generic-python-lib,_torch
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,generic-python-lib,_transformers
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,ml-model,neural-magic,zoo,_model-stub.zoo:nlp/question_answering/obert-large/pytorch/huggingface/squad/pruned95-none-vnni
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,dataset,squad,original
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,dataset-aux,squad-vocab
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src,_deeplearningexamples
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> generate,user-conf,mlperf,inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,loadgen
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,mlcommons,inference,src,_deeplearningexamples
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_deepsparse_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,generic-python-lib,_deepsparse
    get-generic-python-lib,94b62a682bc44791_(_package.pydantic_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,generic-python-lib,_package.pydantic
    get-generic-python-lib,94b62a682bc44791_(_tokenization_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,generic-python-lib,_tokenization
    get-generic-python-lib,94b62a682bc44791_(_six_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,generic-python-lib,_six
    get-generic-python-lib,94b62a682bc44791_(_package.absl-py_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> get,generic-python-lib,_package.absl-py
    detect-cpu,586c8a43320142f7 --> detect,os
    benchmark-program,19f369ef47084895 --> detect,cpu
    benchmark-program-mlperf,cfff0132a8aa4018 --> benchmark-program,program
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_deepsparse,_bert-99,_int8,_offline_) --> benchmark-mlperf