graph TD
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,mlcommons,inference,src
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> pull,git,repo
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,mlperf,inference,utils
    get-cuda,46d133d9ef92422d_(_toolkit_) --> detect,os
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,generic-python-lib,_pip
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,cuda-devices,_with-pycuda
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,mlcommons,inference,src
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> pull,git,repo
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> generate,user-conf,mlperf,inference
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,generic-python-lib,_package.pycuda
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,cuda,_cudnn
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,tensorrt
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> detect,cpu
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,sys-utils-cm
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,cuda,_cudnn
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,tensorrt,_dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,gcc
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,cmake
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_glog-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_gflags-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_libgmock-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_libre2-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_libnuma-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_libboost-all-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_rapidjson-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    get-generic-python-lib,94b62a682bc44791_(_package.pybind11_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_package.pybind11
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> get,generic-python-lib,_pip
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> get,cuda
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_pycuda
    get-generic-python-lib,94b62a682bc44791_(_opencv-python_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_opencv-python
    get-generic-python-lib,94b62a682bc44791_(_nvidia-dali_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_nvidia-dali
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_nlohmann-json3-dev
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic,sys-util,_git-lfs
    get-generic-python-lib,94b62a682bc44791_(_package.torch,_whl-url.https://github.com/mlcommons/cm4mlperf-inference/releases/download/mlperf-inference-v4.0/torch-2.1.0a0+git32f93b1-cp38-cp38-linux_x86_64.whl_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_package.torch,_whl-url.https://github.com/mlcommons/cm4mlperf-inference/releases/download/mlperf-inference-v4.0/torch-2.1.0a0+git32f93b1-cp38-cp38-linux_x86_64.whl
    get-generic-python-lib,94b62a682bc44791_(_package.torchvision,_whl-url.https://github.com/mlcommons/cm4mlperf-inference/releases/download/mlperf-inference-v4.0/torchvision-0.16.0a0+657027f-cp38-cp38-linux_x86_64.whl_) --> get,python3
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> get,generic-python-lib,_package.torchvision,_whl-url.https://github.com/mlcommons/cm4mlperf-inference/releases/download/mlperf-inference-v4.0/torchvision-0.16.0a0+657027f-cp38-cp38-linux_x86_64.whl
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> detect,cpu
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,sys-utils-cm
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,python3
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,cuda,_cudnn
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,tensorrt
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,cmake
    get-generic-python-lib,94b62a682bc44791_(_requests_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_requests_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_requests_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_requests_) --> get,generic-python-lib,_pip
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic-python-lib,_requests
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_glog-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_gflags-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_libre2-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_libnuma-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_libboost-all-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic,sys-util,_rapidjson-dev
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    get-generic-python-lib,94b62a682bc44791_(_pycuda_) --> get,python3
    add-custom-nvidia-system,b2e6c46c6e8745a3_(_mlcommons_) --> get,generic-python-lib,_pycuda
    build-mlperf-inference-server-nvidia,f37403af5e9f4541_(_mlcommons_) --> add,custom,system,nvidia,_mlcommons
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> build,nvidia,inference,server,_mlcommons
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,mlcommons,inference,src
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> pull,git,repo
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.pycuda
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,cuda,_cudnn
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,tensorrt
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> build,nvidia,inference,server,_mlcommons
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,mlcommons,inference,src
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> pull,git,repo
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,generic-python-lib,_pip
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.nibabel
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,generic-python-lib,_pip
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_pandas
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,generic-python-lib,_pip
    get-generic-python-lib,94b62a682bc44791_(_package.nvidia-pyindex_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,generic-python-lib,_package.nvidia-pyindex
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_onnx-graphsurgeon
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> get,generic-python-lib,_pip
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.onnx
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> save,mlperf,inference,state
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> reproduce,mlperf,inference,nvidia,harness,_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,mlcommons,inference,src
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> pull,git,repo
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.nibabel
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_pandas
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_onnx-graphsurgeon
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.onnx
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev_) --> save,mlperf,inference,state
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> reproduce,mlperf,inference,nvidia,harness,_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.nibabel
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_pandas
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_onnx-graphsurgeon
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.onnx
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev_) --> save,mlperf,inference,state
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> reproduce,mlperf,inference,nvidia,harness,_build_engine,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_batch_size.1,_3d-unet_,_v4.1-dev
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> reproduce,mlperf,inference,nvidia,harness,_preprocess_data,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> reproduce,mlperf,inference,nvidia,harness,_download_model,_3d-unet-99.9,_cuda,_tensorrt,_3d-unet_,_v4.1-dev
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,generic-python-lib,_package.nibabel
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,generic-python-lib,_pandas
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,generic-python-lib,_onnx-graphsurgeon
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> get,generic-python-lib,_package.onnx
    detect-cpu,586c8a43320142f7 --> detect,os
    benchmark-program,19f369ef47084895 --> detect,cpu
    benchmark-program-mlperf,cfff0132a8aa4018 --> benchmark-program,program
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_3d-unet-99.9,_cuda,_tensorrt,_singlestream,_rtx_4090_) --> benchmark-mlperf