graph TD
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> get,mlcommons,inference,src
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> get,mlperf,inference,utils
    app-mlperf-inference,d775cac873ee4231_(_cpp,_resnet50,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> get,dataset-aux,imagenet-aux
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_singlestream,_resnet50,_onnxruntime_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_singlestream,_resnet50,_onnxruntime_) --> detect,cpu
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_singlestream,_resnet50,_onnxruntime_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_singlestream,_resnet50,_onnxruntime_) --> get,loadgen
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_singlestream,_resnet50,_onnxruntime_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_singlestream,_resnet50,_onnxruntime_) --> get,lib,onnxruntime,lang-cpp,_cpu
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_singlestream,_resnet50,_onnxruntime_) --> get,dataset,preprocessed,imagenet,_NCHW,_full
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_singlestream,_resnet50,_onnxruntime_) --> get,ml-model,raw,resnet50,_onnx
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_cpu,_singlestream,_resnet50,_onnxruntime_) --> generate,user-conf,mlperf,inference