graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_tf,_cpu,_valid,_r5.0-dev_default,_offline_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_tf,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_tf,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_tf,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,mlcommons,inference,src
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_tf,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,mlperf,inference,utils
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_tf,_cpu,_valid,_r5.0-dev_default,_offline_) --> get,dataset-aux,imagenet-aux
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,python
    get-generic-python-lib,94b62a682bc44791_(_tensorflow_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,generic-python-lib,_tensorflow
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,ml-model,image-classification,resnet50,raw,_fp32,_tf
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,dataset,image-classification,imagenet,preprocessed,_-for.mobilenet,_full,_NHWC
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,dataset-aux,image-classification,imagenet-aux
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> generate,user-conf,mlperf,inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,loadgen
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_opencv-python_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,generic-python-lib,_opencv-python
    get-generic-python-lib,94b62a682bc44791_(_numpy_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,generic-python-lib,_numpy
    get-generic-python-lib,94b62a682bc44791_(_pycocotools_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,generic-python-lib,_pycocotools
    get-generic-python-lib,94b62a682bc44791_(_protobuf_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_offline,_resnet50,_tf,_cpu,_fp32_) --> get,generic-python-lib,_protobuf