graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_pointpainting,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_pointpainting,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_pointpainting,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_reference,_pointpainting,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,mlcommons,inference,src
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_reference,_pointpainting,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,mlperf,inference,utils
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_reference,_pointpainting,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,cuda-devices,_with-pycuda
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,python
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,cuda,_cudnn
    get-generic-python-lib,94b62a682bc44791_(_torch_cuda_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_torch_cuda
    get-generic-python-lib,94b62a682bc44791_(_torchvision_cuda_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_torchvision_cuda
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,ml-model,pointpainting
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,dataset,waymo
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> generate,user-conf,mlperf,inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,loadgen
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_package.shapely_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.shapely
    get-generic-python-lib,94b62a682bc44791_(_package.numba_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.numba
    get-generic-python-lib,94b62a682bc44791_(_package.open3d_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.open3d
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,generic-python-lib,_pip
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.numpy
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,generic-python-lib,_pip
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.numpy
    get-generic-python-lib,94b62a682bc44791_(_package.tensorboard_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.tensorboard
    get-generic-python-lib,94b62a682bc44791_(_package.onnxruntime_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.onnxruntime
    get-generic-python-lib,94b62a682bc44791_(_package.opencv-python_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.opencv-python
    get-generic-python-lib,94b62a682bc44791_(_package.scikit-image_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.scikit-image
    get-generic-python-lib,94b62a682bc44791_(_package.scipy_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.scipy
    get-generic-python-lib,94b62a682bc44791_(_package.ninja_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-python-lib,_package.ninja
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-sys-util,_ffmpeg
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-sys-util,_libsm6
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_pytorch,_singlestream,_pointpainting,_fp32_) --> get,generic-sys-util,_libxext6