graph TD
    app-mlperf-inference,d775cac873ee4231_(_cpp,_retinanet,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_cpp,_retinanet,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_cpp,_retinanet,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_cpp,_retinanet,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> get,mlcommons,inference,src
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_cpp,_retinanet,_onnxruntime,_cpu,_valid,_r5.0-dev_default,_singlestream_) --> get,mlperf,inference,utils
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> detect,cpu
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> get,loadgen
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> get,lib,onnxruntime,lang-cpp,_cpu
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> get,dataset,preprocessed,openimages,_validation,_NCHW,_full
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> get,ml-model,retinanet,_onnx,_fp32
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> generate,user-conf,mlperf,inference
    detect-cpu,586c8a43320142f7 --> detect,os
    compile-program,c05042ba005a4bfa --> detect,cpu
    compile-program,c05042ba005a4bfa --> get,compiler,gcc
    detect-cpu,586c8a43320142f7 --> detect,os
    get-compiler-flags,31be8b74a69742f8 --> detect,cpu
    compile-program,c05042ba005a4bfa --> get,compiler-flags
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> compile,cpp-program
    detect-cpu,586c8a43320142f7 --> detect,os
    benchmark-program,19f369ef47084895 --> detect,cpu
    benchmark-program-mlperf,cfff0132a8aa4018 --> benchmark-program,program
    app-mlperf-inference-mlcommons-cpp,bf62405e6c7a44bf_(_retinanet,_onnxruntime,_cpu,_singlestream_) --> benchmark-mlperf