graph TD
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,mlcommons,inference,src
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> pull,git,repo
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,mlperf,inference,utils
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_nvidia,_3d-unet-99.9,_tensorrt,_cuda,_valid,_r5.0-dev_default,_singlestream_) --> get,cuda-devices,_with-pycuda
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,mlcommons,inference,src
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> pull,git,repo
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> generate,user-conf,mlperf,inference
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_package.pycuda
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,cuda,_cudnn
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,tensorrt
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> build,nvidia,inference,server,_mlcommons
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,mlcommons,inference,src
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> pull,git,repo
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.pycuda
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,cuda,_cudnn
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,tensorrt
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> build,nvidia,inference,server,_mlcommons
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,mlcommons,inference,src
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> pull,git,repo
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,generic-python-lib,_pip
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.nibabel
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,generic-python-lib,_pip
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_pandas
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_onnx-graphsurgeon
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.onnx
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> save,mlperf,inference,state
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> reproduce,mlperf,inference,nvidia,harness,_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> detect,cpu
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,sys-utils-cm
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,mlperf,inference,nvidia,scratch,space,_version.5.0-dev
    get-generic-python-lib,94b62a682bc44791_(_mlperf_logging_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_mlperf_logging
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,mlcommons,inference,src
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,nvidia,mlperf,inference,common-code,_mlcommons
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> pull,git,repo
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.nibabel
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_pandas
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_onnx-graphsurgeon
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.onnx
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev_) --> save,mlperf,inference,state
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> reproduce,mlperf,inference,nvidia,harness,_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.nibabel
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_pandas
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_onnx-graphsurgeon
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> get,generic-python-lib,_package.onnx
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev_) --> save,mlperf,inference,state
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> reproduce,mlperf,inference,nvidia,harness,_build_engine,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_batch_size.1,_3d-unet_,_v4.1-dev
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> reproduce,mlperf,inference,nvidia,harness,_preprocess_data,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> reproduce,mlperf,inference,nvidia,harness,_download_model,_cuda,_3d-unet-99.9,_tensorrt,_3d-unet_,_v4.1-dev
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_transformers
    get-generic-python-lib,94b62a682bc44791_(_package.nibabel_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_package.nibabel
    get-generic-python-lib,94b62a682bc44791_(_pandas_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_pandas
    get-generic-python-lib,94b62a682bc44791_(_onnx-graphsurgeon_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_onnx-graphsurgeon
    get-generic-python-lib,94b62a682bc44791_(_package.onnx_) --> get,python3
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> get,generic-python-lib,_package.onnx
    detect-cpu,586c8a43320142f7 --> detect,os
    benchmark-program,19f369ef47084895 --> detect,cpu
    benchmark-program-mlperf,cfff0132a8aa4018 --> benchmark-program,program
    app-mlperf-inference-nvidia,bc3b17fb430f4732_(_run_harness,_singlestream,_cuda,_3d-unet-99.9,_tensorrt,_rtx_4090_) --> benchmark-mlperf